#!/bin/sh

npm run eslint
if [ $? != 0 ]
then
    echo "Lint failed rejecting commit"
    exit 1
fi
npm run test
if [ $? != 0 ]
then
    echo "Tests failed rejecting commit"
    exit 1
fi
# look for: 'fit(', 'fit (', 'fdescribe(', 'fdescribe ('
find tst/ -name '*.js' -exec cat {} \; | egrep '(fit|fdescribe)\s?\('
if [ $? = 0 ]
then
    echo "Focused it or describe found in tests"
    exit 1
fi
exit 0