#!/bin/sh

npm run eslint
if [ $? != 0 ]
then
    echo "Lint failed rejecting commit"
    exit 1
fi
npm run test
if [ $? != 0 ]
then
    echo "Tests failed rejecting commit"
    exit 1
fi
# look for: '(x|f)it(', '(x|f)it (', '(x|f)describe(', '(x|f)describe ('
find tst/ -name '*.js' -exec cat {} \; | egrep '(f|x)(it|describe)\s?\('
if [ $? = 0 ]
then
    echo "(Focused or Excluded) it or describe found in tests"
    exit 1
fi
exit 0