const FRANCO_ARAB_REMINDME_VARIANTS = [
    'fakarny', 'fakrny', 'fkarny', 'fkrny',
    'fakarney', 'fakrney', 'fkraney', 'fkrney',
    'fakarni', 'fakrni', 'fkrani', 'fkrni',
    'fakarnei', 'fakrnei', 'fkrnaei', 'fkrnei',
];

const EVENTS = {
    ASK_TO_START_TUTORIAL_COMMAND: "ASK_TO_START_COMMAND",
    YES_COMMAND: "YES_COMMAND",
    NO_COMMAND: "NO_COMMAND",
    TIMEZONE_VALID: "TIMEZONE_VALID",
    REMINDER_VALID: "REMINDER_VALID",
    END_TUTORIAL_COMMAND: "END_TUTORIAL_COMMAND",
};

const TUTORIAL = {
    STATES: {
        NOT_IN_TUTORIAL: "NOT_IN_TUTORIAL",
        TUTORIAL_INITIATION: "TUTORIAL_INITIATION",
        SET_TIMEZONE: "SET_TIMEZONE",
        SET_REMINDER: "SET_REMINDER",
        EDIT_REMINDER_TIME: "EDIT_REMINDER_TIME",
        SET_REMINDER_WITH_SHORTCUT: "SET_REMINDER_WITH_SHORTCUT",
        EXIT_TUTORIAL: "EXIT_TUTORIAL",
    }
};

module.exports = {
    FRANCO_ARAB_REMINDME_VARIANTS: FRANCO_ARAB_REMINDME_VARIANTS,
    EVENTS: EVENTS,
    TUTORIAL: TUTORIAL
};
